repos:
      - repo: https://github.com/PyCQA/isort
        rev: 5.12.0  # New version tags can be found here: https://github.com/PyCQA/isort/tags
        hooks:
              - id: isort
                name: isort (import sorting)
                additional_dependencies: [toml]
      - repo: https://github.com/pycqa/flake8
        rev: 6.0.0  # New version tags can be found here: https://github.com/pycqa/flake8/tags
        hooks:
              - id: flake8
                name: flake8 (code linting)
      - repo: https://github.com/psf/black
        rev: 22.12.0  # New version tags can be found here: https://github.com/psf/black/tags
        hooks:
              - id: black
                name: black (code formatting)
